version: '3.8'

services:
  dam:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: docker.io/feyyum/dam:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    platform: linux/amd64