[package]
name = "tlsn-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
log = "0.4"
env_logger = "0.10"

[[bin]]
name = "tlsn-api"
path = "src/lib.rs"